code optimized

diff --git a/kode b/kode
--- a/kode
+++ b/kode
@@ -20,41 +20,40 @@ DATE=$(date '+%a %d %b %y  %R:%S')
 
 header_template()
 {
-        printf "************************************************#\n"
-        printf "#%-49s#\n"
-        printf "%-16s %s %-30s %s\n" "#  Project title" ':'  $1 '#'
-        printf "%-16s %s %-30s %s\n" "#  Author" ':' "${AUTHOR}" '#'
-        printf "%-16s %s %-30s %s\n" "#  Date" ':'  "${DATE}" '#'
-        printf "%-16s %s %-30s %s\n" "#  Last modified" ':'  "${DATE}" '#'
-        printf "%-16s %s %-30s %s\n" "#  Notes" ":" ""  '#'
-        printf "%-16s %s %-30s %s\n" "#  Description" ':' "" '#'
-        printf "#%-49s#\n"
-        printf "#************************************************"
+    printf "************************************************#\n"
+    printf "#%-49s#\n"
+    printf "%-16s %s %-30s %s\n" "#  Project title" ':'  $1 '#'
+    printf "%-16s %s %-30s %s\n" "#  Author" ':' "${AUTHOR}" '#'
+    printf "%-16s %s %-30s %s\n" "#  Date" ':'  "${DATE}" '#'
+    printf "%-16s %s %-30s %s\n" "#  Last modified" ':'  "${DATE}" '#'
+    printf "%-16s %s %-30s %s\n" "#  Notes" ":" ""  '#'
+    printf "%-16s %s %-30s %s\n" "#  Description" ':' "" '#'
+    printf "#%-49s#\n"
+    printf "#************************************************"
 
 }
 
 insert_shebang_header()
 {
-	#checking if shebang required
+    #checking if shebang required
     if [[ "$1" =~ \.(pl|py|rb|sh)$ ]]
-      then
-		#checking environment
-		[[ "$1" =~ \.pl$ ]] && environment=perl
-		[[ "$1" =~ \.py$ ]] && environment=python3
-		[[ "$1" =~ \.rb$ ]] && environment=ruby
-		[[ "$1" =~ \.sh$ ]] && environment=bash
-		
+    then
+        #checking environment
+        [[ "$1" =~ \.pl$ ]] && environment=perl
+        [[ "$1" =~ \.py$ ]] && environment=python3
+        [[ "$1" =~ \.rb$ ]] && environment=ruby
+        [[ "$1" =~ \.sh$ ]] && environment=bash
 
-		#appending shebang
-                echo -e "#!$(which env) $environment\n" >> $1
-		#appending header template
-                echo -e "#*$(header_template $1)*#\n" >> $1
-    
+        #appending shebang
+        echo -e "#!$(which env) $environment\n" >> $1
+        #appending header template
+        echo -e "#*$(header_template $1)*#\n" >> $1
+
     elif [[ "$1" =~ \.(c|cpp|cs|css|java|js|php|rs|swift|ts)$ ]]
-      then
-      #shebang not requied
-      #appending header template only
-      echo -e "/*$(header_template $1)*/\n" >> $1
+    then
+        #shebang not requied
+        #appending header template only
+        echo -e "/*$(header_template $1)*/\n" >> $1
 
     fi
 }
@@ -62,101 +61,101 @@ insert_shebang_header()
 
 set_author()
 {
-        clear
-        echo -e "\n${R} ≫${W} Enter author's name :${OFF} \c"
-        read AUTHOR_NAME
+    clear
+    echo -e "\n${R} ≫${W} Enter author's name :${OFF} \c"
+    read AUTHOR_NAME
 
-        AUTHOR_NAME=$(printf "%.30s" "$AUTHOR_NAME")
+    AUTHOR_NAME=$(printf "%.30s" "$AUTHOR_NAME")
 
-	#replacing author name in kodeconfig file
-        sed -i "0,/^AUTHOR.*/{s//AUTHOR=\"${AUTHOR_NAME}\"/}" ~/.kodeconfig
-        echo -e "${G} ≫${W} Author name $AUTHOR_NAME set successfully."
+    #replacing author name in kodeconfig file
+    sed -i "0,/^AUTHOR.*/{s//AUTHOR=\"${AUTHOR_NAME}\"/}" ~/.kodeconfig
+    echo -e "${G} ≫${W} Author name $AUTHOR_NAME set successfully."
 }
 
 set_text_editor()
 {
-        false
-        while [ $? -gt 0 ]
-        do
-                clear
-                echo -e "\n${R} ≫${W} Enter text editor :${OFF} \c"
-                read
+    false
+    while [ $? -gt 0 ]
+    do
+        clear
+        echo -e "\n${R} ≫${W} Enter text editor :${OFF} \c"
+        read
 
-                which $REPLY > /dev/null
-                if [ $? -gt 0 ];then
-                        echo -e "${R} ≫ error${W} : $REPLY not found" >&2
-                        echo -ne "   try again\r"
-                        sleep 2
+        which $REPLY > /dev/null
+        if [ $? -gt 0 ];then
+            echo -e "${R} ≫ error${W} : $REPLY not found" >&2
+            echo -ne "   try again\r"
+            sleep 2
 
-                else
-			#replacing editor in kodeconfig file
-                        sed -i "0,/^TXT_EDITOR.*/{s//TXT_EDITOR=${REPLY}/}" ~/.kodeconfig
-                        echo -e "${G} ≫${W} $REPLY set successfully."
+        else
+            #replacing editor in kodeconfig file
+            sed -i "0,/^TXT_EDITOR.*/{s//TXT_EDITOR=${REPLY}/}" ~/.kodeconfig
+            echo -e "${G} ≫${W} $REPLY set successfully."
 
-                fi
-                which $REPLY > /dev/null
-        done
+        fi
+        which $REPLY > /dev/null
+    done
 }
 
 
 
 update_last_modified()
 {
-        REPLACE_WITH=$(printf "%-16s %s %-30s %s\n" "#  Last modified" ':'  "${DATE}" '#')
+    REPLACE_WITH=$(printf "%-16s %s %-30s %s\n" "#  Last modified" ':'  "${DATE}" '#')
 
-        #update first occurrence of last modified
-        sed -i "0,/^#  Last modified.*/{s//${REPLACE_WITH}/}" ${1}
-}
+    #update first occurrence of last modified
+    sed -i "0,/^#  Last modified.*/{s//${REPLACE_WITH}/}" ${1}
+    }
 
 file_exists()
 {
-        md5sum1="$(printf "%.33s" $(md5sum $1))"
+    md5sum1="$(printf "%.33s" $(md5sum $1))"
 
-        $TXT_EDITOR "$1"
+    $TXT_EDITOR "$1"
 
-        md5sum2="$(printf "%.33s" $(md5sum $1))"
+    md5sum2="$(printf "%.33s" $(md5sum $1))"
 
-        if [[ ${new} == "true" && "$md5sum1" == "$md5sum2" ]]
-        then
-                rm -f $1
+    if [[ ${new} == "true" && "$md5sum1" == "$md5sum2" ]]
+    then
+        rm -f $1
 
-        elif [[ "$md5sum1" != "$md5sum2" ]]
-        then
-                update_last_modified $1
-        fi
+    elif [[ "$md5sum1" != "$md5sum2" ]]
+    then
+        update_last_modified $1
+    fi
 }
 
 is_new_file()
 {
-        touch "$1"
-        chmod u+x $1  #making file executable
+    touch "$1"
+    chmod u+x $1  #making file executable
 
-        insert_shebang_header $1 #inserting shebang
+    insert_shebang_header $1 #inserting shebang
 
-        new="true"
-        file_exists $1
+    new="true"
+    file_exists $1
 
 }
 
 help()
 {
-        echo -e "Usage : ${W}kode${OFF} [option] [file...]"
-        echo -e " -h    --help      Print help"
-        echo -e " -v    --version   Print version"
-        echo -e " -a    --author    Set author name"
-        echo -e " -e    --editor    Set editor"
+    echo -e "Usage : ${W}kode${OFF} [option] [file...]"
+    echo -e " -h    --help      Print help"
+    echo -e " -v    --version   Print version"
+    echo -e " -a    --author    Set author name"
+    echo -e " -e    --editor    Set editor"
 }
 
 version()
 {
-        echo "kode v2.2"
-        echo "A bash script to add header and shebang in your codes."
-        echo "Author : https://github.com/laraib07"
-	echo
-	echo "Supported languages : "
-	echo "bash, c, c++, c#, css, java, "
-	echo "javascript, perl, php, python, "
-	echo "ruby, rust, swift, typescript."
+    echo "kode v2.2"
+    echo "A bash script to add header and shebang in your codes."
+    echo "Author : https://github.com/laraib07"
+    echo
+    echo "Supported languages : "
+    echo "bash, c, c++, c#, css, java, "
+    echo "javascript, perl, php, python, "
+    echo "ruby, rust, swift, typescript."
 }
 
 
@@ -166,40 +165,40 @@ which ${TXT_EDITOR} > /dev/null || TXT_EDITOR="$DEFAULT_TXT_EDITOR"
 #if no argument provided
 if [[ -z "$1" ]]
 then
-	echo "No argument provided."
-	echo "Provide atleast one argument."
+    echo "No argument provided."
+    echo "Provide atleast one argument."
 fi
 
 #driver code
 while [[ -n "$1" ]]
 do
-        case $1 in
-                "-h" | "--help" )
-                        help ;;
+    case $1 in
+        "-h" | "--help" )
+            help ;;
 
-                "-v" | "--version" )
-                        version ;;
+        "-v" | "--version" )
+            version ;;
 
-                "-a" | "--author" )
-                        set_author ;;
+        "-a" | "--author" )
+            set_author ;;
 
-                "-e" | "--editor" )
-                        set_text_editor ;;
+        "-e" | "--editor" )
+            set_text_editor ;;
 
-                [!-]* )
-                        if [[ -f "$1" ]]; then
-				file_exists $1
-                        else
-				is_new_file  $1
-                        fi
-                        ;;
+        [!-]* )
+            if [[ -f "$1" ]]; then
+                file_exists $1
+            else
+                is_new_file  $1
+            fi
+            ;;
 
-                * )
-                        echo "$1 is Invalid Option" >&2
-                        echo "Try \"-h\" or \"--help\" for Help!"
-                        echo
-        esac
-        shift
+        * )
+            echo "$1 is Invalid Option" >&2
+            echo "Try \"-h\" or \"--help\" for Help!"
+            echo
+    esac
+    shift
 done
 
 exit 0
